"""empty message

Revision ID: c6a4e5e3465c
Revises: dc1f1f789bad
Create Date: 2021-12-02 15:40:32.470496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a4e5e3465c'
down_revision = 'dc1f1f789bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'profile', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profile', type_='unique')
    # ### end Alembic commands ###
